export const manhwas = [
    {
        id: "solo-leveling",
        title: "Solo Leveling",
        source: "asura",
        description: "10 years ago, after “the Gate” that connected the real world with the monster world opened, some of the ordinary, everyday people received the power to hunt monsters within the Gate. They are known as \"Hunters\". My title is Sung Jin-Woo, an E-rank Hunter. Changing from the weakest Hunter to the strongest S-rank Hunter!",
        genres: ["Action", "Adventure", "Fantasy", "Shounen"],
        status: "Completed",
    },
    {
        id: "the-regressed-mercenarys-machinations",
        title: "The Regressed Mercenary's Machinations",
        source: "asura",
        description: "Ghislain Perdium, the Mercenary King and one of the continent's top seven, started a great war in an attempt to avenge his fallen family. With this second chance, he decided to fix all the wrong pieces of the puzzle and avoid making the same mistakes he did in his past life!",
        genres: ["Action", "Adventure", "Fantasy", "Regression", "Revenge"],
        status: "Ongoing",
    },
    {
        id: "reaper-of-the-drifting-moon",
        title: "Reaper of the Drifting Moon",
        source: "asura",
        description: "He's in the deepest part of the Jianghu. Keep your eyes wide open if you do not wish to get dragged into the abyss.",
        genres: ["Action", "Fantasy", "Genius MC", "Martial Arts", "Murim"],
        status: "Ongoing",
    },
    {
        id: "the-divine-demons-grand-ascension",
        title: "The Divine Demon’s Grand Ascension",
        source: "asura",
        description: "While Bu Eunseol was still young, he lost his grandfather to a mysterious killer. For revenge, he will devour the martial arts of the ten demon sects and endure countless bloodshed to become the strongest.",
        genres: ["Action", "Adventure", "Fantasy", "Martial Arts", "Murim", "Revenge"],
        status: "Ongoing",
    },
    {
        id: "swordmasters-youngest-son",
        title: "Swordmaster’s Youngest Son",
        source: "asura",
        description: "Jin Runcandel was the youngest son of Runcandel, the land's most prestigious swordsman family... And the biggest failure in Runcandel history. Memories of his past life, overwhelming talent, and a contract with God... The preparations to become the greatest are complete.",
        genres: ["Action", "Another chance", "Fantasy", "Overpowered", "Returned", "Shounen"],
        status: "Ongoing",
    },
    {
        id: "nano-machine",
        title: "Nano Machine",
        source: "asura",
        description: "Nanotechnology meets martial arts at the Mashin Academy. Will a mysterious nanomachine injection from a future descendent help Yeo-un in this fierce competition against his powerful half-siblings?",
        genres: ["Action", "Adventure", "Fantasy", "Martial Arts", "Murim", "System"],
        status: "Ongoing",
    },
    {
        id: "the-world-after-the-end",
        title: "The World After The End",
        source: "asura",
        description: "This is about a man who didn't regress when everyone else returned back to the past. Humans were suddenly summoned to become “Walkers”, and they needed to clear the tower to save the world.",
        genres: ["Action", "Adventure", "Fantasy", "Shounen"],
        status: "Ongoing",
    },
    {
        id: "absolute-regression",
        title: "Absolute Regression",
        source: "asura",
        description: "\"Please send me back to the past.\" If he cannot kill that person in this era, he just needs to go back to the past. This is his first step to taking his revenge.",
        genres: ["Action", "Adventure", "Fantasy", "Martial Arts", "Murim", "Regression", "Revenge"],
        status: "Ongoing",
    },
    {
        id: "after-the-moonlight-falls-trial",
        title: "After the Moonlight Falls",
        source: "asura",
        description: "“Welcome to the world of the Mad Moon!” After losing his entire family to vampires, Segun is reborn as a vampire hunter. Will he become a vampire, or die as a human?",
        genres: ["Action", "Fantasy", "Noble"],
        status: "Ongoing (TRIAL)",
    },
    {
        id: "childhood-friend-of-the-zenith",
        title: "Childhood Friend of the Zenith",
        source: "asura",
        description: "Gu Yangchun, who betrayed the Orthodox sects, became a demonic human under the Heavenly Demon. Realizing his regression was not a dream, Gu Yangchun decided to live a quiet life.",
        genres: ["Action", "Fantasy", "Martial Arts", "Wuxia"],
        status: "Ongoing",
    },
    {
        id: "absolute-sword-sense",
        title: "Absolute Sword Sense",
        source: "asura",
        description: "After being given up on by his family because his dantian was destroyed, Soh Woonhwi was kidnapped by the Blood Cult. He returned to the day he was kidnapped ten years ago and obtained a mysterious ability that allowed him to hear the voice of swords.",
        genres: ["Action", "Adventure", "Martial Arts", "Murim", "Returner"],
        status: "Ongoing",
    },
    {
        id: "reformation-of-the-deadbeat-noble",
        title: "Reformation of the Deadbeat Noble",
        source: "asura",
        description: "Airen Parreira is a boy who sleeps to run away from reality. People mocked him, calling him a ‘deadbeat’, but he had no wish to change. Until one day, he dreamt of a swordsman…",
        genres: ["Action", "Adventure"],
        status: "Hiatus",
    },
    {
        id: "doctors-rebirth",
        title: "Doctor’s Rebirth",
        source: "asura",
        description: "I had been abroad to do medical volunteer work, when I was swept up in a civil war. This is the story of how I became the greatest physician in Gangho!",
        genres: ["Action", "Adventure", "Fantasy", "Isekai", "Martial Arts"],
        status: "Ongoing",
    },
    {
        id: "star-embracing-swordmaster",
        title: "Star-Embracing Swordmaster",
        source: "asura",
        description: "Vlad was a vagrant child of the slums who always admired knights. After an incident where he was struck by black lightning, he began hearing a voice.",
        genres: ["Action", "Adventure", "Fantasy", "Genius MC"],
        status: "Ongoing",
    },
    {
        id: "the-return-of-the-crazy-demon",
        title: "The Return of the Crazy Demon",
        source: "asura",
        description: "Yi Zaha. The crazy demon crazy for martial arts. The crazy demon who returned to the beginning of his days as a waiter! Will he go crazy again, or will he drive his enemies crazy?",
        genres: ["Action", "Adventure", "Comedy", "Demon", "Martial Arts", "Returner"],
        status: "Ongoing",
    },
    {
        id: "omniscient-readers-viewpoint",
        title: "Omniscient Reader’s Viewpoint",
        source: "asura",
        description: "‘This is a development that I know of.’ The moment he thought that the world had been destroyed, a new universe had unfolded.",
        genres: ["Action", "Adventure", "Fantasy"],
        status: "Ongoing",
    },
    {
        id: "the-shepherd-wizard",
        title: "The Shepherd Wizard",
        source: "asura",
        description: "There stood a seemingly ordinary shepherd titled Turan from Hisaril Hill. Having lived while hiding his talent as a great archwizard, he finally steps out into the world.",
        genres: ["Action", "Adventure", "Fantasy", "Magic", "Mystery"],
        status: "Ongoing",
    },
    {
        id: "bad-born-blood",
        title: "Bad Born Blood",
        source: "asura",
        description: "Humanity's home is no longer Earth. Intersellar travel is now a common occurence, and technology has replaced blood and flesh. Luka's aptitude is of the \"Imperial Guard.\"",
        genres: ["Action", "Adventure", "Fantasy", "Sci-fi"],
        status: "Ongoing",
    },
    {
        id: "surviving-as-a-genius-on-borrowed-time",
        title: "Surviving as a Genius on Borrowed Time",
        source: "asura",
        description: "Jung Yeonshin was born with a short fate: being unable to live past the age of twenty. This is where Jung Yeonshin, a terminally-ill genius, begins his desperate struggle to survive!",
        genres: ["Action", "Adventure", "Genius MC", "Martial Arts", "Murim"],
        status: "Ongoing",
    },
    {
        id: "myst-might-mayhem",
        title: "Myst, Might, Mayhem",
        source: "asura",
        description: "Jeong, the Slaughtering Scythe Demon, feels joy in killing others. The serial killer begins his new life as the third young master of the great Mok Sword Manor.",
        genres: ["Action", "Adventure", "Crazy MC", "Fantasy", "Martial Arts", "Murim"],
        status: "Ongoing",
    },
    {
        id: "the-regressed-son-of-a-duke-is-an-assassin",
        title: "The Regressed Son of a Duke is an Assassin",
        source: "asura",
        description: "Cyan Vert, the best assassin of the continent, meets a pitiful death after having been betrayed by his own brother. Given a second chance, he will pave a path on his own!",
        genres: ["Action", "Adventure", "Fantasy", "Regression", "Revenge"],
        status: "Ongoing",
    },
    {
        id: "eternally-regressing-knight",
        title: "Eternally Regressing Knight",
        source: "asura",
        description: "Encrid dreamed of becoming a knight, but he soon realized it was futile. One day, he died, having been stabbed in the neck. Encrid opened his eyes again to \"today's\" morning.",
        genres: ["Action", "Adventure", "Fantasy", "Regression"],
        status: "Ongoing",
    },
    {
        id: "revenge-of-the-iron-blooded-sword-hound",
        title: "Revenge of the Iron-Blooded Sword Hound",
        source: "asura",
        description: "He was the hound of the Baskerville family: Vikir. Yet his loyalty was rewarded by the blade of a guillotine dirtied by slander. It's time for the hound to exact bloody revenge.",
        genres: ["Action", "Adventure", "Fantasy", "Martial Arts", "Returner", "Revenge", "Supernatural"],
        status: "Ongoing",
    },
    {
        id: "murim-psychopath",
        title: "Murim Psychopath",
        source: "asura",
        description: "When he tried returning to virtual reality, the place he logged into was instead the “real Murim.” A once-in-an-era psychopath fell into the Murim due to the Grim Reaper’s mistake.",
        genres: ["Action", "Adventure", "Fantasy", "Crazy MC", "Martial Arts", "Murim", "Psychological"],
        status: "Ongoing",
    },
    {
        id: "magic-academys-genius-blinker",
        title: "Magic Academy's Genius Blinker",
        source: "asura",
        description: "The character with the highest difficulty and the worst performance, Baek Yuseol, was considered a trash character in-game because he could not use magic. Surviving in Stella Academy among genius mages, I became the notorious Blink Mage.",
        genres: ["Action", "Adventure", "Fantasy", "Genius MC", "School Life", "Supernatural"],
        status: "Ongoing",
    },
    {
        id: "chronicles-of-the-lazy-sovereign",
        title: "Chronicles of the Lazy Sovereign",
        source: "asura",
        description: "The great warrior who ended the chaos that plagued the world—that is Wi Yeonho, the Radiant Martial Sovereign. The shocking truth behind the so-called greatest chivalrous warrior is revealed!",
        genres: ["Action", "Adventure", "Martial Arts", "Murim"],
        status: "Ongoing",
    },
    {
        id: "murim-login",
        title: "Murim Login",
        source: "asura",
        description: "An era where hunters thrive on hunting monsters that come from Gates. Jin Tae-Kyung is a low-rank hunter who picks up a VR machine, and accidentally logs into the game.",
        genres: ["Action", "Adventure", "Comedy", "Fantasy", "Martial Arts", "Seinen"],
        status: "Ongoing",
    },
    {
        id: "bloodhounds-regression-instinct",
        title: "Bloodhound's Regression Instinct",
        source: "asura",
        description: "\"Yan,\" the protagonist, was brainwashed by the emperor and lived as his puppet. After finding out he was being played, he planned to seek revenge.",
        genres: ["Action", "Adventure", "Fantasy", "Regression", "Revenge"],
        status: "Completed",
    },
    {
        id: "the-greatest-estate-developer",
        title: "The Greatest Estate Developer",
        source: "asura",
        description: "When civil engineering student Suho Kim falls asleep reading a fantasy novel, he wakes up as a character in the book! Suho is now in the body of Lloyd Frontera.",
        genres: ["Action", "Adventure", "Comedy", "Fantasy"],
        status: "Completed",
    },
    {
        id: "overpowered-sword",
        title: "Overpowered Sword",
        source: "asura",
        description: "The protagonist of a story is always decided from the start. No matter how hard the supporting role tries, they'll just be a supporting role in the end. Then, a moment came where all of that changed.",
        genres: ["Action", "Adventure", "Fantasy", "Overpowered"],
        status: "Hiatus",
    },
    {
        id: "return-of-the-mount-hua-sect",
        title: "Return of the Mount Hua Sect",
        source: "asura",
        description: "Chung Myung, The 13th Disciple of the Mount Hua Sect, defeated Chun Ma. He is reborn after 100 years in the body of a child. What? The Mount Hua Sect has fallen?",
        genres: ["Action", "Adventure", "Comedy", "Fantasy", "Martial Arts", "Rebirth", "Shounen"],
        status: "Hiatus",
    },
    {
        id: "pick-me-up-infinite-gacha",
        title: "Pick Me Up, Infinite Gacha",
        source: "asura",
        description: "The mobile gacha game 'Pick Me Up!' is known for being brutally difficult. Upon waking up, Loki finds himself turned into a 1-star level 1 hero, 'Islat Han'.",
        genres: ["Action", "Adventure", "Comedy", "Fantasy", "System"],
        status: "Ongoing",
    },
    {
        id: "the-extras-academy-survival-guide",
        title: "The Extra’s Academy Survival Guide",
        source: "asura",
        description: "I possessed a third-rate extra villain character in my favorite game. I have no ambitions and I just want to live a quiet life. But sheesh, this world is a hard place to survive in.",
        genres: ["Action", "Adventure", "Fantasy", "Supernatural", "Transmigrating"],
        status: "Ongoing",
    },
    {
        id: "ending-maker",
        title: "Ending Maker",
        source: "asura",
        description: "There are two people who were obssessed with the game, Legend of Heroes 2, and spent thousands of hours on it. The journey of the veteran gamers to accomplish the happy ending starts now!",
        genres: ["Action", "Comedy", "Fantasy", "Romance", "Video Game"],
        status: "Hiatus",
    },
    {
        id: "demonic-beast-hunter-survival-guide",
        title: "Demonic Beast Hunter Survival Guide",
        source: "asura",
        description: "For 12 years, Woojin suffered from mysterious nightmares of unknown origin. When he opened his eyes, he found himself inside the very world from his nightmares—the \"Demon Realm.\"",
        genres: ["Action", "Adventure", "Fantasy", "Mystery"],
        status: "Ongoing",
    },
    {
        id: "sandmancer-of-the-scorched-desert",
        title: "Sandmancer of the Scorched Desert",
        source: "asura",
        description: "A thrilling tale of tactical magic manipulation set inside an unforgiving, arid ecosystem.",
        genres: ["Action", "Adventure", "Fantasy", "Magic"],
        status: "Ongoing",
    },
    {
        id: "mgeko__a-returner-s-magic-should-be-special-mg1-njfia",
        title: "A Returner's Magic Should Be Special",
        source: "mgeko",
        description: "Desir Arman is one of the last remaining human survivors inside the Shadow Labyrinth. He is suddenly sent back 13 years into the past.",
        genres: ["Action", "Adventure", "Fantasy", "Magic", "School Life"],
        status: "Completed",
    },
    {
        id: "mgeko__absolute-dominion",
        title: "Absolute Dominion",
        source: "mgeko",
        description: "A grand epic detailing a relentless protagonist's rise to absolute supremacy across the martial landscape.",
        genres: ["Action", "Martial Arts", "Murim", "Overpowered"],
        status: "Ongoing",
    },
    {
        id: "mgeko__bowblade-spirit-mg12",
        title: "Bowblade Spirit",
        source: "mgeko",
        description: "Raised by his grandfather in the remote mountains, a young archer trains tirelessly with the legendary Bowblade technique before entering Jianghu.",
        genres: ["Action", "Adventure", "Martial Arts", "Wuxia"],
        status: "Completed",
    },
    {
        id: "mgeko__bowblade-the-descendants-of-bowblade-manhwa",
        title: "The Descendants of Bowblade",
        source: "mgeko",
        description: "The official sequel tracking the dangerous path of the legendary Bowblade legacy's descendants.",
        genres: ["Action", "Adventure", "Martial Arts", "Murim"],
        status: "Ongoing",
    },
    {
        id: "mgeko__chronicles-of-the-heavenly-demon",
        title: "Chronicles of the Heavenly Demon",
        source: "mgeko",
        description: "Unjustly executed, Woon-Seong is reincarnated as an apprentice within the Demonic Cult, embarking on a path of absolute vengeance.",
        genres: ["Action", "Adventure", "Martial Arts", "Murim", "Revenge"],
        status: "Ongoing",
    },
    {
        id: "mgeko__eleceed",
        title: "Eleceed",
        source: "mgeko",
        description: "Jiwoo is a kind-hearted high schooler who possesses lightning-fast reflexes. Kayden is a brilliant international ranker trapped inside the body of a cat.",
        genres: ["Action", "Comedy", "Supernatural", "School Life"],
        status: "Ongoing",
    },
    {
        id: "mgeko__existence",
        title: "Existence",
        source: "mgeko",
        description: "After living countless lives over millions of years as everything from an insect to a giant beast, a powerful entity finally reincarnates into a human boy.",
        genres: ["Action", "Drama", "Fantasy", "Supernatural"],
        status: "Completed",
    },
    {
        id: "mgeko__gosuff",
        title: "Gosu",
        source: "mgeko",
        description: "A young martial artist sets out to avenge his master's betrayal, only to discover that the traitors have all apparently already died.",
        genres: ["Action", "Comedy", "Martial Arts", "Murim"],
        status: "Completed",
    },
    {
        id: "mgeko__her-summon",
        title: "Her Summon",
        source: "mgeko",
        description: "An otaku dealing with severe social anxiety finds himself suddenly summoned into a magical fantasy dimension where his normal build gives him god-like capabilities.",
        genres: ["Action", "Adventure", "Comedy", "Fantasy", "Isekai"],
        status: "Completed",
    },
    {
        id: "mgeko__infinite-level-up-in-murim",
        title: "Infinite Level Up in Murim",
        source: "mgeko",
        description: "Dan Yuseong dies a miserable death on a chaotic battlefield. He wakes up in the past with a video-game-styled RPG level-up system attached to his soul.",
        genres: ["Action", "Adventure", "Martial Arts", "Murim", "Regression", "System"],
        status: "Ongoing",
    },
    {
        id: "mgeko__legend-of-the-northern-blade",
        title: "Legend of the Northern Blade",
        source: "mgeko",
        description: "When the world plunged into darkness, martial artists gathered to form the Northern Heavenly Sect. After its tragic fall, Jin Mu-Won uncovers the secret wall arts left behind by his father to exact ultimate retribution.",
        genres: ["Action", "Adventure", "Martial Arts", "Murim", "Revenge"],
        status: "Ongoing",
    },
    {
        id: "mgeko__leviathan",
        title: "Leviathan",
        source: "mgeko",
        description: "Earth has been completely submerged by a catastrophic rising global ocean. Deep below the waves, terrifying aquatic monsters rule the deep sea, forcing the remnants of humanity to harvest and fight for survival on ships.",
        genres: ["Action", "Adventure", "Sci-fi", "Dystopian", "Post-Apocalyptic"],
        status: "Completed",
    },
    {
        id: "mgeko__martial-artist-lee-gwak",
        title: "Martial Artist Lee Gwak",
        source: "mgeko",
        description: "Lee Gwak is a plain, low-ranking guard who loses the function of his limbs after being brutally beaten by a superior martial artist. Refusing to give up, he slowly rebuilds his physical foundation through unique breathing and persistence.",
        genres: ["Action", "Martial Arts", "Murim", "Historical"],
        status: "Completed",
    },
    {
        id: "mgeko__memoir-of-the-king-of-war",
        title: "Memoir of the King of War",
        source: "mgeko",
        description: "Dan Sa-Yu, the supreme successor of the ancient martial art Celestial Battle Combat, steps into the Central Plains to search for his lost childhood friend, leaving an absolute trail of broken bones and vanquished foes.",
        genres: ["Action", "Martial Arts", "Murim", "Overpowered"],
        status: "Ongoing",
    },
    {
        id: "mgeko__mercenary-enrollment-mg12",
        title: "Mercenary Enrollment",
        source: "mgeko",
        description: "Yu Ijin was the sole survivor of a tragic childhood plane crash. After spending ten brutal years working as a highly lethal mercenary in foreign warzones, he returns home to live a peaceful life with his family and attend high school.",
        genres: ["Action", "Drama", "School Life", "Military"],
        status: "Ongoing",
    },
    {
        id: "mgeko__noblesse",
        title: "Noblesse",
        source: "mgeko",
        description: "Cadis Etrama Di Raizel, an ancient, powerful vampire noble, awakens from an 820-year deep slumber in modern South Korea. He attempts to blend in as an ordinary high school student alongside his loyal servant, Frankenstein.",
        genres: ["Action", "Comedy", "Supernatural", "School Life", "Vampire"],
        status: "Completed",
    },
    {
        id: "mgeko__player-mg1",
        title: "Player",
        source: "mgeko",
        description: "Heor Seol-Jin is a cynical webtoon comment-section troll who is suddenly dragged directly into the fantasy comic world he criticized, instantly forced to play the deadly game as an unranked candidate.",
        genres: ["Action", "Adventure", "Fantasy", "Comedy", "System"],
        status: "Ongoing",
    },
    {
        id: "mgeko__promised-orchid",
        title: "Promised Orchid",
        source: "mgeko",
        description: "Yang Jaesin is plagued by recurring, hyper-realistic nightmares of a distant past. His life shifts permanently when he gains the sight to perceive supernatural mythical specters and mythical creatures lurking in the seams of modern Seoul.",
        genres: ["Action", "Supernatural", "Fantasy", "Mystery", "Romance"],
        status: "Completed",
    },
    {
        id: "mgeko__regressed-life-of-the-sword-clans-ignoble-reincarnator",
        title: "Regressed Life of the Sword Clan's Ignoble Reincarnator",
        source: "mgeko",
        description: "Born into a legendary family of unrivaled swordsmen but lacking the fundamental talent to match them, our protagonist meets an untimely, tragic end—only to return straight to his youth with a renewed determination to master the blade.",
        genres: ["Action", "Adventure", "Fantasy", "Regression"],
        status: "Ongoing",
    },
    {
        id: "mgeko__sword-sheath-s-child-mg1",
        title: "Sword Sheath's Child",
        source: "mgeko",
        description: "Bira is a wild, pure child who loves fishing and wanders the scenic wilderness with his adoptive grandfather. His peaceful world shatters into absolute chaos when he is thrown headfirst into the ancient internal feuds of the Murim world.",
        genres: ["Action", "Adventure", "Fantasy", "Martial Arts"],
        status: "Ongoing",
    },
    {
        id: "mgeko__the-beginning-after-the-end",
        title: "The Beginning After The End",
        source: "mgeko",
        description: "King Grey, a powerful ruler in a highly advanced sci-fi world, suddenly passes away and reincarnates as Arthur Leywin into a fantasy world of magic, swords, elves, and vicious mythical beasts.",
        genres: ["Action", "Adventure", "Fantasy", "Isekai", "Magic", "School Life"],
        status: "Ongoing",
    },
    {
        id: "mgeko__the-boxer",
        title: "The Boxer",
        source: "mgeko",
        description: "Yu is an emotionally empty, hollow teenager with unmatched raw talent for visual processing and physical movement. Under the training of a legendary boxing coach, he enters the world of professional boxing, obliterating opponents.",
        genres: ["Action", "Drama", "Psychological", "Sports"],
        status: "Completed",
    },
    {
        id: "mgeko__the-breaker",
        title: "The Breaker",
        source: "mgeko",
        description: "Shi-Woon Yi is a weak, relentlessly bullied high school boy who accidentally witnesses the terrifying martial arts prowess of his eccentric new substitute teacher, Chun-Woo Han, and begs to become his disciple.",
        genres: ["Action", "Drama", "Martial Arts", "School Life", "Murim"],
        status: "Completed",
    },
    {
        id: "mgeko__the-breaker-eternal-force",
        title: "The Breaker: Eternal Force",
        source: "mgeko",
        description: "The thrilling third installment of the legendary Breaker series. As Shi-Woon grapples with his massive responsibilities inside the complex Murim alliance, a brand-new generation of martial arts users steps onto the scene.",
        genres: ["Action", "Drama", "Martial Arts", "Murim", "School Life"],
        status: "Ongoing",
    },
    {
        id: "mgeko__the-breaker-new-waves",
        title: "The Breaker: New Waves",
        source: "mgeko",
        description: "The direct second season following the events of The Breaker. Left with a completely shattered center of martial power, Shi-Woon must navigate the dangerous power vacuums and deadly targeted attacks of the subterranean Murim underworld.",
        genres: ["Action", "Drama", "Martial Arts", "Murim", "School Life"],
        status: "Completed",
    },
    {
        id: "mgeko__the-god-of-high-school",
        title: "The God of High School",
        source: "mgeko",
        description: "Jin Mori is a high school student and renewal taekwondo expert who enters an open-bracket fighting tournament to determine the absolute strongest high school martial artist on Earth, uncovering cosmic, god-like conspiracies along the way.",
        genres: ["Action", "Adventure", "Comedy", "Fantasy", "Martial Arts", "Supernatural"],
        status: "Completed",
    },
    {
        id: "mgeko__the-long-way-of-the-warrior",
        title: "The Long Way of the Warrior",
        source: "mgeko",
        description: "An authentic, highly immersive, gritty historical martial arts journey that charts a wandering mercenary's long and blood-splattered road toward true warrior enlightenment.",
        genres: ["Action", "Martial Arts", "Historical", "Drama"],
        status: "Ongoing",
    },
    {
        id: "mgeko__the-story-of-a-low-rank-soldier-becoming-a-monarch",
        title: "The Story of a Low-Rank Soldier Becoming a Monarch",
        source: "mgeko",
        description: "Chris is a battle-worn mercenary soldier who loses his arm and ultimately his life on a disastrous battlefield. He wakes up 24 years in the past as his teenage self, armed with his memories and an interactive technical system.",
        genres: ["Action", "Adventure", "Fantasy", "Regression", "System"],
        status: "Ongoing",
    },
    {
        id: "mgeko__tower-of-god",
        title: "Tower of God",
        source: "mgeko",
        description: "Twenty-Fifth Bam enters the ominous, monolithic Tower to find his closest childhood friend Rachel, who abandoned him. He must climb each brutally competitive, high-stakes floor, encountering lethal monsters and ancient gods.",
        genres: ["Action", "Adventure", "Fantasy", "Mystery", "Supernatural"],
        status: "Ongoing",
    },
    {
        id: "mgeko__urek-s-ascent",
        title: "Urek's Ascent",
        source: "mgeko",
        description: "A specialized side-story or spin-off adventure focusing heavily on dynamic, hyper-powered ascension mechanics within a perilous fantasy universe.",
        genres: ["Action", "Adventure", "Fantasy", "Overpowered"],
        status: "Ongoing",
    },
    {
        id: "mgeko__wind-breaker",
        title: "Wind Breaker",
        source: "mgeko",
        description: "Jay is a straight-A student and perfect student council president who is secretly a highly gifted street cyclist. He is roped into joining the local street racing crew, discovering a massive underground cycling subculture.",
        genres: ["Action", "Drama", "Sports", "School Life", "Comedy"],
        status: "Axed",
    },
    {
        id: "mgeko__yongbi-the-invincible",
        title: "Yongbi the Invincible",
        source: "mgeko",
        description: "Yongbi is a quirky, highly unpredictable bounty hunter traveling with his absurdly intelligent horse. Beneath his greedy, comedic exterior lies a devastatingly powerful former military commander of the Black Spear Lancers.",
        genres: ["Action", "Adventure", "Comedy", "Martial Arts", "Murim", "Historical"],
        status: "Completed",
    }
];

export function searchHardcodedManhwa(query) {
    const q = query.toLowerCase().trim();
    if (!q) return manhwas;

    return manhwas.filter(m => {
        const title = (m.title || '').toLowerCase();
        const description = (m.description || '').toLowerCase();
        const genres = (m.genres || []).join(' ').toLowerCase();

        return title.includes(q) || description.includes(q) || genres.includes(q);
    });
}

export function getManhwaById(id) {
    return manhwas.find(m => m.id === id) || null;
}