export const COVER_URLS = {
    "absolute-regression":                                          "https://imgsrv4.com/avatar/288x412/media/manga_covers/w7p5RM-m.jpg",
    "absolute-sword-sense":                                         "https://imgsrv4.com/avatar/288x412/media/manga_covers/absolute-sword-sense.jpg",
    "after-the-moonlight-falls-trial":                              "https://imgsrv4.com/avatar/288x412/media/manga_covers/qis.webp",
    "bad-born-blood":                                               "https://imgsrv4.com/avatar/288x412/media/manga_covers/bad-born-blood.webp",
    "bloodhounds-regression-instinct":                              "https://imgsrv4.com/avatar/288x412/media/manga_covers/bloodhounds-regression-instinct.png",
    "childhood-friend-of-the-zenith":                               "https://imgsrv4.com/avatar/288x412/media/manga_covers/01J4ET0WWYF24VMZG57YWQK46F-thumb-small.webp",
    "chronicles-of-the-lazy-sovereign":                             "https://imgsrv4.com/avatar/288x412/media/manga_covers/chronicles-of-the-lazy-sovereign3.webp",
    "doctors-rebirth":                                              "https://imgsrv4.com/avatar/288x412/media/manga_covers/doctors-rebirth-mg1-2.jpg",
    "ending-maker":                                                 "https://imgsrv4.com/avatar/288x412/media/manga_covers/55651.jpg",
    "eternally-regressing-knight":                                  "https://imgsrv4.com/avatar/288x412/media/manga_covers/sa.jpg",
    "immortals-way-of-life":                                        "https://imgsrv4.com/avatar/288x412/media/manga_covers/immortals-way-of-life.6b50e7.webp",
    "killer-pietro":                                                "https://imgsrv4.com/avatar/288x412/media/manga_covers/Killer-Peter-208x300.webp",
    "magic-academys-genius-blinker":                                "https://imgsrv4.com/avatar/288x412/media/manga_covers/Magic-Academys-Genius-Blinker.webp",
    "murim-login":                                                  "https://imgsrv4.com/avatar/288x412/media/manga_covers/sasasa.webp",
    "murim-psychopath":                                             "https://imgsrv4.com/avatar/288x412/media/manga_covers/01KDQX23G3TC2676XJXA08ZBZ1-optimized.webp",
    "myst-might-mayhem":                                            "https://imgsrv4.com/avatar/288x412/media/manga_covers/myst-might-mayhem.jpg",
    "nano-machine":                                                 "https://imgsrv4.com/avatar/288x412/media/manga_covers/nano-machine.png",
    "omniscient-readers-viewpoint":                                 "https://imgsrv4.com/avatar/288x412/media/manga_covers/l_30.jpg",
    "overpowered-sword":                                            "https://imgsrv4.com/avatar/288x412/media/manga_covers/overpowered-sword.png",
    "pick-me-up-infinite-gacha":                                    "https://imgsrv4.com/avatar/288x412/media/manga_covers/pick-me-up.png",
    "reaper-of-the-drifting-moon":                                  "https://imgsrv4.com/avatar/288x412/media/manga_covers/reaper-moon-drift.jpg",
    "reformation-of-the-deadbeat-noble":                            "https://imgsrv4.com/avatar/288x412/media/manga_covers/reformation-of-the-deadbeat-noble-23.png",
    "return-of-the-mount-hua-sect":                                 "https://imgsrv4.com/avatar/288x412/media/manga_covers/return-of-the-mount-hua-sect-2.gif",
    "revenge-of-the-iron-blooded-sword-hound":                      "https://imgsrv4.com/avatar/288x412/media/manga_covers/revenge-of-the-iron-blooded-sword-hound.png",
    "sandmancer-of-the-scorched-desert":                            "https://imgsrv4.com/avatar/288x412/media/manga_covers/tk9t-sandmancer-of-the-scorched-desert.jpg",
    "solo-leveling":                                                "https://imgsrv4.com/avatar/288x412/media/manga_covers/k722631932_2.jpg",
    "star-embracing-swordmaster":                                   "https://cdn.asurascans.com/asura-images/covers/star-embracing-swordmaster.6b1222-400.webp",
    "surviving-as-a-genius-on-borrowed-time":                       "https://imgsrv4.com/avatar/288x412/media/manga_covers/01J8XKNNRNH3JG7YXXDS776164-optimized.webp",
    "swordmasters-youngest-son":                                    "https://imgsrv4.com/avatar/288x412/media/manga_covers/swordmasters-youngest-son.jpg",
    "the-divine-demons-grand-ascension":                            "",
    "the-extras-academy-survival-guide":                            "https://imgsrv4.com/avatar/288x412/media/manga_covers/zuski.jpg",
    "the-greatest-estate-developer":                                "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1725185056i/218343539.jpg",
    "the-regressed-mercenarys-machinations":                        "https://imgsrv4.com/avatar/288x412/media/manga_covers/01J8FFNN5BR0T6NF6PVTRKJ29M-optimized.webp",
    "the-regressed-son-of-a-duke-is-an-assassin":                   "https://imgsrv4.com/avatar/288x412/media/manga_covers/the-regressed-son-of-a-duke-is-an-assassn.jpg",
    "the-return-of-the-crazy-demon":                                "https://imgsrv4.com/avatar/288x412/media/manga_covers/hababababbaba.jpg",
    "the-shepherd-wizard":                                          "https://imgsrv4.com/avatar/288x412/media/manga_covers/01KJ5AER3RGKM5T6954QGC8TMB-optimized.webp",
    "the-world-after-the-end":                                      "https://imgsrv4.com/avatar/288x412/media/manga_covers/the-world-after-the-fall.jpeg",




    "mgeko__a-returner-s-magic-should-be-special-mg1-njfia":        "https://imgsrv4.com/avatar/288x412/media/manga_covers/a-returner-s-magic-should-be-speci.png",
    "mgeko__absolute-dominion":                                     "https://imgsrv4.com/avatar/288x412/media/manga_covers/Absolute-Dominion-193x278.webp",
    "mgeko__bowblade-spirit-mg12":                                  "https://imgsrv4.com/avatar/288x412/media/manga_covers/bowblade-spirit.jpeg",
    "mgeko__bowblade-the-descendants-of-bowblade-manhwa":           "",
    "mgeko__chronicles-of-the-heavenly-demon":                      "https://imgsrv4.com/avatar/288x412/media/manga_covers/z8BXN1RoQEdn7MO4EZSqR6jhXX0B35RuqlYFnu3T.png",
    "mgeko__eleceed":                                               "https://imgsrv4.com/avatar/288x412/media/manga_covers/eleceed-2.jpg",
    "mgeko__existence":                                             "https://imgsrv4.com/avatar/288x412/media/manga_covers/existence.png",
    "mgeko__gosuff":                                                "https://imgsrv4.com/avatar/288x412/media/manga_covers/53759_104294_422.jpg",
    "mgeko__her-summon":                                            "https://imgsrv4.com/avatar/288x412/media/manga_covers/b77447525f4e89334ba7c70cd857.jpg",
    "mgeko__infinite-level-up-in-murim":                            "https://imgsrv4.com/avatar/288x412/media/manga_covers/61609.png",
    "mgeko__legend-of-the-northern-blade":                          "https://imgsrv4.com/avatar/288x412/media/manga_covers/49273.jpg",
    "mgeko__leviathan":                                             "https://imgsrv4.com/avatar/288x412/media/manga_covers/Leviathansd.jpg",
    "mgeko__martial-artist-lee-gwak":                               "https://imgsrv4.com/avatar/288x412/media/manga_covers/martial-artist-lee-gwak.jpg",
    "mgeko__memoir-of-the-king-of-war":                             "https://imgsrv4.com/avatar/288x412/media/manga_covers/MGW.gif",
    "mgeko__mercenary-enrollment-mg12":                             "https://imgsrv4.com/avatar/288x412/media/manga_covers/rxG82.jpg",
    "mgeko__noblesse":                                              "https://imgsrv4.com/avatar/288x412/media/manga_covers/Noblesse_manhwa_Cover.jpg",
    "mgeko__player-mg1":                                            "https://imgsrv4.com/avatar/288x412/media/manga_covers/player-2.gif",
    "mgeko__promised-orchid":                                       "https://imgsrv4.com/avatar/288x412/media/manga_covers/39190.png",
    "mgeko__regressed-life-of-the-sword-clans-ignoble-reincarnator":"https://imgsrv4.com/avatar/288x412/media/manga_covers/YgEJNM-m.jpg",
    "mgeko__sword-sheath-s-child-mg1":                              "https://imgsrv4.com/avatar/288x412/media/manga_covers/sword-sheath-s-child-mg1-1.png",
    "mgeko__the-beginning-after-the-end":                           "https://imgsrv4.com/avatar/288x412/media/manga_covers/v8prB3-m.jpg",
    "mgeko__the-boxer":                                             "https://imgsrv4.com/avatar/288x412/media/manga_covers/unnamed_SgIWf4Q.jpg",
    "mgeko__the-breaker":                                           "https://imgsrv4.com/avatar/288x412/media/manga_covers/the-breaker.jpg",
    "mgeko__the-breaker-eternal-force":                             "",
    "mgeko__the-breaker-new-waves":                                 "https://imgsrv4.com/avatar/288x412/media/manga_covers/7b97bd9ce57cf74d699f3e6cce885a12.jpg",
    "mgeko__the-god-of-high-school":                                "https://imgsrv4.com/avatar/288x412/media/manga_covers/7237.jpg",
    "mgeko__the-long-way-of-the-warrior":                           "https://imgsrv4.com/avatar/288x412/media/manga_covers/EZl6_AKU4AEs1mw_1_UN5J0Ac.jpg",
    "mgeko__the-story-of-a-low-rank-soldier-becoming-a-monarch":    "https://imgsrv4.com/avatar/288x412/media/manga_covers/3BroBzXSEWQee6ujDYeD7HyJho10NKXtEng4vXgC.jpeg",
    "mgeko__tower-of-god":                                          "https://imgsrv4.com/avatar/288x412/media/manga_covers/tower-of-god-7810.png",
    "mgeko__urek-s-ascent":                                         "https://imgsrv4.com/avatar/288x412/media/manga_covers/w7X8BX-m.jpg",
    "mgeko__wind-breaker":                                          "https://imgsrv4.com/avatar/288x412/media/manga_covers/kRx1Dy-m.jpg",
    "mgeko__yongbi-the-invincible":                                 "https://imgsrv4.com/avatar/288x412/media/manga_covers/yongbi-the-invincible.webp",
};




export function getCoverUrl(seriesId) {
    return COVER_URLS[seriesId] || null;
}

